#!/bin/bash

echo "Start install...";
sudo pacman -S qbittorrent nautilus deepin-file-manager firefox gftp gimp inkscape rawtherapee fontforge blender deepin-picker gnac audacity sonic-visualiser canorus musescore vlc ciano handbrake gaupol libsndfile jhead exiv2 mediainfo-gui mediainfo alacritty file-roller gitg geany ghex jq umbrello gucharmap gnome-multi-writer neofetch hardinfo usbview gnome-font-viewer abiword libreoffice-still bluegriffon scribus gnome-books gnome-documents clamav clamtk rkhunter gnome-nettool nmap xorg-xcalc geogebra root units stellarium;
echo "Goodbye!";
